spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=yj_application
    username: myuser
    password: Q!dudwls3012
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
